### ISSUE TITLE
some question about rnn

### ISSUE THREAD

**Issue by HeGaoYuan** [saebrahimi/Emotion-Recognition-RNN#3]
In your RNN folder, the 

> rnn_on_convnet_features_multi_frame.py,

https://github.com/saebrahimi/Emotion-Recognition-RNN/blob/master/RNN/rnn_on_convnet_features_multi_frame.py#L14
your code is `from rnn_multi_frame import RNN`, but I can not find the rnn_multi_frame module,
I think it should be `from rnn import RNN`

**Comment by saebrahimi** [comment]
Sorry for the missing file. We experimented with a lot of settings including concatenating successive frames into windows but simple RNN with window size 1 worked best.
I uploaded the missing file.
