### ISSUE TITLE
some question about early stopping when training CNN

### ISSUE THREAD

**Issue by HeGaoYuan** [saebrahimi/Emotion-Recognition-RNN#4]
Hi, 
I have read your paper and I have some confusion on **2.1.3 CNN Architecture**.

> Therefore, for our best CNN structure, we trained on all FER+TFD and performed early stopping on  AFEW-faces train+validation.

As we all know, the AFEW-faces are clipped in the video, and the video labels are targeted to individual frames. So I think it is not good to perform early stopping on AFEW-faces, because the the labels of AFEW-faces have too much noise. Why didn't you split the FER+TFD as training and validation, and perform early stopping on the validation.

And another question is that how you decide the early stopping? I am trying to use **no-improvement-in-five epoch rule** .
Thank you! Look forward to your reply!

**Comment by saebrahimi** [comment]
We agree that early stopping on the noisy per-frame target of AFEW-faces might not be perfect.
As far as I remember this option performed the best so we validated on AFEW-faces.

We trained for 1000 epochs and save the model parameters when we find a new best on validation data.
