### ISSUE TITLE
where'/home/vincent/data/emotiw2015/Datasets/convnet_data.h5'?

### ISSUE THREAD

**Issue by jinqiu11** [saebrahimi/Emotion-Recognition-RNN#5]
Now,I'm studing your paper Recurrent Neural Networks for Emotion Recognition in Video  .And I'M doing the expreiment accoroding with the code in the github.But I can't find the  
'/home/vincent/data/emotiw2015/Datasets/convnet_data.h5''/home/vincent/data/emotiw2015/Datasets/fertfd_mean_std.h5'

**Comment by saebrahimi** [comment]
These two files are output files, that are generated by the script
_CNN/prep_data_for_convnet.py_

You need to adjust the filenames to your own folder structure.

The _convnet_data.h5_ might be an artifact from an older version, so you could comment the following block to save some time:
https://github.com/saebrahimi/Emotion-Recognition-RNN/blob/master/CNN/prep_data_for_convnet.py#L38-L42

Vincent added the file _ CNN/dump_convnet_full_train.py_ that we forgot to commit, which generates the full training and validation data for the CNN.

Please don't hesitate to ask, if there are further questions

**Comment by jinqiu11** [comment]
I understand  it.Thank  you  very much.
